### ISSUE TITLE
Cancelling payment with Internet Banking

### ISSUE THREAD

**Issue by SzamanSZ** [omise/omise-magento#104]
In Magento 1.x, using the newest plugin (multicurrency), when I choose Internet Banking, cancel even on bank login page and go back to Merchant, I am redirected to success page without paying.

**Comment by guzzilar** [comment]
@SzamanSZ Hi, thanks for your report, I can also reproduce this issue.

**Comment by SzamanSZ** [comment]
Any approximation about when this issue will be fixed?

**Comment by jacekstan** [comment]
closing as bug is fixed.
