### ISSUE TITLE
Can not Place order with Omise payment

### ISSUE THREAD

**Issue by kinhcan** [omise/omise-magento#116]
Hi team,
We installed Omise payment follow step by step of your document and config it. But extension not working for me. After choose payment method when checkout, it not working. I got error:

message
:
"An error occurred on the server. Please try to place the order again."
trace
:
`"#0 /var/www/html/magento2.1.6/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(3, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#1 /var/www/html/magento2.1.6/var/generation/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#2 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(3, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address))↵#3 /var/www/html/magento2.1.6/vendor/magento/module-webapi/Controller/Rest.php(307): call_user_func_array(Array, Array)↵#4 /var/www/html/magento2.1.6/vendor/magento/module-webapi/Controller/Rest.php(216): Magento\Webapi\Controller\Rest->processApiRequest()↵#5 /var/www/html/magento2.1.6/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#6 /var/www/html/magento2.1.6/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#7 /var/www/html/magento2.1.6/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()↵#8 /var/www/html/magento2.1.6/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))↵#9 {main}"`
Thanks!

**Comment by jacekstan** [comment]
Hi,

Thank you for your bug report.
Could you please tell me a bit more about your testing environment (server)?

Also, it look a bit like your server lost an internet connection for the time you were testing?

**Comment by kinhcan** [comment]
Hi,
Thank for your reply
We using local to test your extension. Is it running at local?
If can not, We will install at server, and check again

**Comment by kinhcan** [comment]
Hi Team,
We installed your extension at server, and get same error 
You use the details below for testing:

```
Name: JOHN DOE
Number: 4242424242424242
Expired month: 12
Expired year: 2020
Security code: 123
```

**Comment by kinhcan** [comment]
Hi team,
We can change minimum amount for transaction? 
`amount must be greater than or equal to 2000 (thb subunits). $0.30 converts to approximately 922 (thb subunits)`

**Comment by kinhcan** [comment]
Thank for your response,
I have a question.
I created 1 recipient by PHP API Code,
```
<?php

$recipient = OmiseRecipient::create(array(
  'name' => 'Omise Tester',
  'description' => 'Tester account',
  'email' => 'tester@omise.co',
  'type' => 'individual',
  'tax_id' => '',
  'bank_account' => array(
    'brand' => 'bbl',
    'number' => '1234567890',
    'name' => 'Tester Account'
  )
));
```

How to login with this recipient account
https://prnt.sc/jizvwu
Thanks!

**Comment by guzzilar** [comment]
@kinhcan Sorry, what do you mean by 'login with the recipient account'?


> And we can update attribute "active" "verified" by API? 

This sounds interesting, we don't have API for activating recipients at the moment.
In order to activate recipient, it can only be done via Omise Dashboard.

**Comment by guzzilar** [comment]
@kinhcan Hi
Recipient is an API to create a recipient object that will be used for money transfer only (not create another Omise account or any login-user).

For example, you are running a marketplace-like business that allow your users to open their own shops at your marketplace and somehow you want to transfer incomes to those users at the end of a month, situation.
This is where Recipient comes, this feature will give you a power to transfer your balance from your Omise account out to those recipients (which, you have already created) as you prefer when time is appropriate.

..
Just in case if you are looking for a sub-account thing that you can hands it to your team that they can log in to the dashboard sharing the same balance, you can check our **"Teams"** feature:
![screen shot 2561-05-18 at 18 58 36](https://user-images.githubusercontent.com/2154669/40233558-b42bc106-5acd-11e8-878a-4552b3b6694c.png)
![screen shot 2561-05-18 at 18 59 09](https://user-images.githubusercontent.com/2154669/40233572-bdb95544-5acd-11e8-8c0e-6ef560a16695.png)

You can create another Omise account and invite them to join your account's team.
That way, you will be able log in to Omise Dashboard with a new user as a team member.


--
I'm not sure if I answer your question appropriately, please feel free to let me know if there is any unclear answers. :))

Cheers.

**Comment by kinhcan** [comment]
Thank for your answer, it is good to understand clearly.

**Comment by guzzilar** [comment]
👍
