### ISSUE TITLE
Checkout Problem With Magento 2.2.5

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#139]
Hello,

My server Setup:
Centos 7
Nginx 1.12.1
Varnish 
Redis
Magento 2.2.6
Php 7.0.30

I have successfully install your module and have configured the admin settings with the test api key. Then i enable credit/debit card.

When i go to checkout on the development server i get the following error:

:8083/rest/default/V1/guest-carts/cf5dc89634d04465a703f7f7ea24412b/payment-information:1 Failed to load resource: the server responded with a status of 500 ()
:8083/checkout/#payment:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.process (error-processor.js:28)
    at Object.<anonymous> (place-order.js:24)
    at fire (jquery.js:3232)
    at Object.fireWith [as rejectWith] (jquery.js:3362)
    at done (jquery.js:9842)
    at XMLHttpRequest.callback (jquery.js:10311)

Upon inspection of the nginx log i found the following error:

2018/07/31 07:26:26 [error] 100651#0: *4657 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OmiseCharge' not found in /var/www/website/web/app/code/Omise/Payment/Model/Api/Charge.php:62
Stack trace:
#0 /var/www/website/web/app/code/Omise/Payment/Gateway/Http/Client/Payment.php(57): Omise\Payment\Model\Api\Charge->create(Array)
#1 /var/www/website/web/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(102): Omise\Payment\Gateway\Http\Client\Payment->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#2 /var/www/website/web/vendor/magento/module-payment/Model/Method/Adapter.php(546): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)
#3 /var/www/website/web/vendor/magento/module-payment/Model/Method/Adapter.php(652): Magento\Payment\Model\Method\Adapter->executeCommand('initialize', Array)
#4 /var/www/website/web/generated/code/Magento/Payment/Model/Method/Adapter/Interceptor.php(557): Magento\Payment\Model\Method\Adapter->initialize('authorize_captu...', Object(Magento\Fram" while reading response header from upstream, client: 183.88.227.221, server: test.website.co.th, request: "POST /rest/default/V1/guest-carts/cf5dc89634d04465a703f7f7ea24412b/payment-information HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "test.website.co.th:8083", referrer: "http://test.website.co.th:8083/checkout/"

Any Ideas?

**Comment by jacekstan** [comment]
Hi,
Thanks for your error submit.

Did you install extension via composer?
or downloaded from github?

can you check if you have omise-php installed (it should be automatically installed if you did use composer)

if not.. you need to install it as it is required external library for the plugin.

Cheers,
Jacek.

**Comment by jacekstan** [comment]
closing as nothing more happened, assuming that installing `omise-php` solved issue
