### ISSUE TITLE
setup:di:compile displays error when install on Magento 2.3

### ISSUE THREAD

**Issue by nisapus** [omise/omise-magento#167]
Hi,

I've tried to setup Omise with Magento 2.3, but found the error when run setup:di:compile.

$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 70.5 MiBPHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/html/magento-23/vendor/omise/omise-magento/Model/Api/Object.php on line 7

Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/magento-23/vendor/omise/omise-magento/Model/Api/Object.php on line 7

FYI, test on Ubuntu 18.04 with PHP 7.2

**Comment by jacstn** [comment]
Thanks @nisapus .... I am on it.. it will be released with next release.
I will let you know soon how to quickly fix it.

**Comment by jacstn** [comment]
closing as fixed
