### ISSUE TITLE
Upgrading from version 2.4 to version 2.5. Class not found 'OmiseCapabilities'

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#173]
Dear Omise,

I have upgraded both omise-php(2.91) and omise magento(2.5) and get the following error
PHP message: PHP Fatal error:  Uncaught Error: Class 'OmiseCapabilities' not found in /var/www/clients/client1/web1/web/vendor/omise/omise-magento/Model/Api/Capabilities.php:13
Stack trace:
#0 /var/www/clients/client1/web1/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(60): Omise\Payment\Model\Api\Capabilities->__construct()
#1 /var/www/clients/client1/web1/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Omise\\Payment\\M...')
#2 /var/www/clients/client1/web1/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Omise\\Payment\\M...')
#3 /var/www/clients/client1/web1/web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Omise\\Payment\\M...')
#4  

I have flush cache, setup upgrade, di:compile, restarted varnish, pushed files to content server and still the same message.

My system setup is:
OS: centos7
PHP: php70w-fpm
Cache: varnish and redis
Magento 2.2.5
CDN: AWS Cloudfront

I have been waiting for this upgrade after you moudle upgraded to 2.4 and had so many problems and now i cannot use it and i cannot downgrade back to 2.4 ?

Please advise

**Comment by jacstn** [comment]
hello.

Sorry about that.. 

Please also update your `omise-php` to the newest version.

https://github.com/omise/omise-php/releases/tag/v2.11.0

**Comment by guzzilar** [comment]
@BrainTurner Hi, Omise-Magento v2.5 now requires for Omise-PHP v2.11.0.
Could you share us how did you upgrade Omise-PHP and Omise-Magento? If it is by composer, you could run: `composer require omise/omise-php:2.11.0` at your Magento root folder to upgrade Omise-PHP to the latest version.

Let me know if there is still a problem after upgrading Omise-PHP to v2.11.0.

**Comment by BrainTurner** [comment]
Thanks for the quick reply. I have required the files like you said however at the checkout page i am getting a blank page with just the logo and the top. There is no logs in nginx and in magento system log there is only main.CRITICAL: Warning: array_merge_recursive(): Argument #2 is not an array in /var/www/clients/client1/web1/web/vendor/magento/module-checkout/Model/CompositeConfigProvider.php on line 38

I have done the following steps flush cache, setup upgrade, di:compile, restarted varnish, pushed files to content server and still the same message.

**Comment by jacstn** [comment]
I have tried to reproduce that error on magento 2.2.5, and I cannot.
I tried with different PHP versions.
inclduding php 7.0 and 7.1.

**Comment by BrainTurner** [comment]
Thank you. I have a custom built dhl shipping module as well. I will remove it and see if that is causing problems.

For the mean time i have had to disable omise :(

**Comment by jacstn** [comment]
ok, so this is fix for your issue.
https://github.com/omise/omise-magento/tree/2-fix-capabilities-config-provider.

We will change our release soon. Sorry for that.

**Comment by BrainTurner** [comment]
Thanks for fixing for me. In this version there is still the big problem that when a user cancels internet banking they get redirected to the success page. Will this be fixed anytime soon?

We had to disable internet banking a few months ago and it casued so many problems.

**Comment by BrainTurner** [comment]
Hello Again :). I have found a new problem. When Cash on Delivery payment method is enable as well as omise credit card and the customer selects COD  we get the following error : an error has occurred on the server. please try again later

In the magento log its the following error main.CRITICAL: Notice: Undefined index: payment_type in /var/www/schmidt.co.th/web/vendor/omise/omise-magento/Observer/TescoPaymentObserver.php on line 49 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: payment_type in /var/www/schmidt.co.th/web/vendor/omise/omise-magento/Observer/TescoPaymentObserver.php on line 49 at /var/www/schmidt.co.th/web/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []

Again i have had to disable the module :(

**Comment by jacstn** [comment]
hello @BrainTurner, 

solution for that error is here:
https://github.com/omise/omise-magento/tree/fix-for-error-when-you-choose-COD

Sorry for that.

**Comment by jacstn** [comment]
Hello @BrainTurner 

We have done new release today.

Feel free to update your plugin.
Sorry for all problems you faced.


Cheers,
Jacek.
