### ISSUE TITLE
Support for 3-D Secure

### ISSUE THREAD

**Issue by fred** [omise/omise-magento#18]
Add support for 3-D Secure redirection

**Comment by dmitry-fedyuk** [comment]
The 3D Secure verification is implemented in my alternative [Magento 2 extension for Omise](https://mage2.pro/c/extensions/omise) (it is compatible with the all Magento 2 versions).

**Comment by guzzilar** [comment]
Note: 3-D Secure feature has been provided at #41 (for Magento CE 1.x series) and #76 (for Magento CE 2.x series).
