### ISSUE TITLE
[BUG] Prevent retrieve authentication while module was not configured or key not added yet

### ISSUE THREAD

**Issue by tuyennn** [omise/omise-magento#189]
### Steps to reproduce
- Magento 2.2.7
- Fresh install module
- Payment was not configured or added any key

### Expected result
- From checkout or every constructor class will not call retrieve or authentication data or anything else, unless the module enabled(key added)

### Actual result
- Got Exception on some __construct while the authentication was called but module was not used(key not added)

![image](https://user-images.githubusercontent.com/4010395/57218375-5989a200-701f-11e9-9ead-3670f80c3832.png)

![image](https://user-images.githubusercontent.com/4010395/57218397-6ad2ae80-701f-11e9-8733-922218610fdd.png)

**Comment by jacstn** [comment]
ok, thank you for your bug report. 
Will investigate and fix it asap.

**Comment by tuyennn** [comment]
@jacstn what is the status of this issue? I have to temporary disable your payment gateway on all our development, staging environments.

**Comment by jacstn** [comment]
fixed.
