### ISSUE TITLE
Version 2.8 dicompile error -  Omise\Payment\Controller\Cards\DeleteAction 

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#211]
Hello,

Env:
Magento 2.2.7
Php 7.1.30

After updating to version 2.8 on di:complie comand we get the following error         

 Omise\Payment\Controller\Cards\DeleteAction
        Extra parameters passed to parent construct: $customerSession. File: /var/www/schmidt.co.th/web/vendor/omise/omise-magento/Controller/Cards/DeleteAction.php

Also not sure if its due to the dicompile error but when i choose internet banking i an not redirected to the banks page. Instead i am redirected to the Magento 2 My Account Page??

Please advise. We have been waiting along time to reactive internet banking

**Comment by jacstn** [comment]
Thanks for this bug report, let me assist you here.

Did you try to do first:
`php bin/magento setup:upgrade`
?

**Comment by BrainTurner** [comment]
Hello Jacstn,

Yes. I first enable maintance mode the php bin/magento setup:upgrade. setup:upgrade runs without a problem

When i run  sudo php bin/magento setup:di:compile it gets to 85% and throws an error

Omise\Payment\Controller\Cards\DeleteAction
                Extra parameters passed to parent construct: $customerSession. File: /var/www/schmidt.co.th/web/vendor/omise/omise-magento/Controller/Cards/DeleteAction.php
Total Errors Count: 1


________________________________

**Comment by jacstn** [comment]
Could you do me a favor please and check what happens if you don't run `di-compile` command.
Just run `setup:upgrade` command, it should automatically clean cache, and go to checkout, please.

**Comment by BrainTurner** [comment]
I just tried.

I still get the same problem with bank transfers. I think it might have something to do with my custom shipping module. As when i disable it everything is ok. This is a real pain.

Everything was ok in version 2.7
________________________________

**Comment by jacstn** [comment]
`custom shipping module` as I understand, developers did this module for you? I wish to debug your problem.

**Comment by BrainTurner** [comment]
So i have done more testing and its not the custom shipping module.

I will debug some more and let you know where i find the problem.


Thanks
________________________________

**Comment by BrainTurner** [comment]
So i have found a couple of errors and will explain what happens.

Step 1: Add items to basket and click checkout
Step 2: Fill in shipping and billing info. Select shipping type
Step 3: Choose Payment Method. Select either Installments or Bank Transfer
Step 4: Choose you bank
Step 5 Click Place order.
Following error on checkout page: The "" value's type is invalid. The "int" type was expected. Verify and try again. 
Error message in exception log file:  ไม่มีเอนทิตีที่มี customerId = 38 {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): ไม่มีเอนทิตีที่มี customerId = 38 at /var/www/*********/web/vendor/magento/framework/Exception/NoSuchEntityException.php:50)"} []

Whats weird is the order is place, no payment taken and you remain on the checkout page. Shipment however not placed.
Also if you tried to click Place order again you get the following error message:
Customer Cart is not active

**Comment by jacstn** [comment]
it looks like your session has expired..

I mean.. you left your webbrowser opened for long time before you finished order, and session expired, is that possible?
could you make sure please you are logged in as customer?
so please do test again, but this time after you login do it immediately - testing

**Comment by BrainTurner** [comment]
The test was login as a customer and seesion definitely was not expired.

This problem does not happen when cash of develiery is used or credit card. Only when internet banking or Installments is selected.
________________________________

**Comment by BrainTurner** [comment]
After turning on debug in backend the payment method sends  this error when you click place order for internet banking:

jquery.storageapi.min.js:2 Uncaught TypeError: Cannot convert undefined or null to object
    at Object.i (jquery.storageapi.min.js:2)
    at Object._callMethod (jquery.storageapi.min.js:2)
    at Object.remove (jquery.storageapi.min.js:2)
    at customer-data.js:182
    at Function._.each._.forEach (underscore.js:145)
    at Object.remove (customer-data.js:181)
    at Object.invalidate (customer-data.js:351)
    at HTMLDocument.<anonymous> (customer-data.js:386)
    at HTMLDocument.dispatch (jquery.js:5087)
    at HTMLDocument.elemData.handle (jquery.js:4895)

Following that error. I disable all javascript bundling and 

omise-offsite-internetbanking-method.js:142 Uncaught TypeError: self.isPlaceOrderActionAllowed is not a function
    at Object.<anonymous> (omise-offsite-internetbanking-method.js:142)
    at fire (jquery.js:3240)
    at Object.fireWith [as rejectWith] (jquery.js:3370)
    at done (jquery.js:9063)
    at XMLHttpRequest.<anonymous> (jquery.js:9303)

Hope that helps a bit more

**Comment by jacstn** [comment]
ok.. thank you.. 
do you have in line `31` in file: `omise-offsite-internetbanking-method.js` following code:
```
            isPlaceOrderActionAllowed: ko.observable(quote.billingAddress() != null),
```

**Comment by BrainTurner** [comment]
Confirmed on line 31.

Maybe this is the final key to unlocking the problem:
GET http://192.168.28.132/en/rest/en/V1/orders//omise-offsite?_=1564125581958 400 (Bad Request)

![Omise2 8_internet_banking](https://user-images.githubusercontent.com/41930785/61933800-eace3c00-afb0-11e9-9bed-fa2dce50fe41.png)

**Comment by Renu05** [comment]
@BrainTurner 
This issue is due to the extra parameter passed in the parent construct.

```
class DeleteAction extends \Magento\Framework\App\Action\Action
{
    const WRONG_REQUEST = 1;

    const WRONG_TOKEN = 2;

    const ACTION_EXCEPTION = 3;

    /**
     * @var array
     */
    private $errorsMap = [];

    /**
     * @var Magento\Customer\Model\Session
     */
    private $customerSession;

    /**
     * @var Omise\Payment\Model\Customer
     */
    private $customer;

    /**
     * @param Context  $context
     * @param Session  $customerSession
     * @param Customer $customer
     */
    public function __construct(
        \Magento\Framework\App\Action\Context $context,
        \Magento\Customer\Model\Session       $customerSession,
        \Omise\Payment\Model\Customer         $customer
    ) {
        parent::__construct($context, customerSession);
```

**Comment by BrainTurner** [comment]
**@Renu05**

Thank you. That has fix the dicompile error. Shall i open a new issue for the order number not being passed for internet banking or will it be fix here?

**Comment by jacstn** [comment]
Thank you @BrainTurner for proposition how to solve this issue.

**Comment by jacstn** [comment]
yes, @BrainTurner I think it is better to keep each of bug in a separated report.
