### ISSUE TITLE
Order Number Not Being Passed For Internet Banking/Installments

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#214]
**Environment:**

PHP 7+
Magento 2.2.7 -> 2.3.2
Nginx
Varnish
Ubuntu 18.04
**Custom Theme**

**Steps to reproduce:**
1.  Add items to cart
2. Click Checkout and login to site
3. Enter Shipping/Billing info
4. Select delivery options
5. Choose internet banking or installment payemnt
6. Click place order

Error:

GET http://********/en/rest/en/V1/orders//omise-offsite?_=1564125581958 400 (Bad Request)

Code causing the problem:

`                    function(response) {
                        var self = this;

                        var serviceUrl = urlBuilder.createUrl(
                            '/orders/:order_id/omise-offsite',
                            {
                                order_id: response
                            }
                        );

`
**Expected Results:**

Customer forwarded to payment gateway

This only happens with version omise-magento 2.8 amd didnt happen in previous versions. If i have a clean installation of magento i cannot reproduce the issue. This issue only happens with a custom theme.

**Comment by jacstn** [comment]
@BrainTurner still exists?
I also sent you private message some time ago.

**Comment by BrainTurner** [comment]
Hi @jacstn 
Sorry for late reply. I did manage to reproduce the issue on a clean install of magento. Its was due to minify HTML and java bundling. I disabled both and it worked in the end

**Comment by aashishgurung** [comment]
We are closing this issue since it's already been resolved. Thank you.
