### ISSUE TITLE
Can't complete place order in Magento 2.3.1 & PHP 7.2

### ISSUE THREAD

**Issue by congbk2910** [omise/omise-magento#245]
I try to complete place order with Internet Banking or Credit/Debit Cart but it's always return "Transaction has been declined. Please try again later.

![omise-issue](https://user-images.githubusercontent.com/37996592/76837755-aa843c80-6865-11ea-99ab-dd362da5f252.png)

**Comment by jacstn** [comment]
Hi @congbk2910 

Could you please try with order value bigger then 20 thb?

**Comment by congbk2910** [comment]
> Hi @congbk2910
> 
> Could you please try with order value bigger then 20 thb?

I have tried but still get the same error :(
![omise-issue-2](https://user-images.githubusercontent.com/37996592/76844771-5cc10180-6870-11ea-81ef-27d8b5fadea6.png)

**Comment by jacstn** [comment]
thanks... could you please check what is in your logging directory? `/var/logs`

and post files here

**Comment by jacstn** [comment]
also, did you install plugin via `composer` or manually?

**Comment by congbk2910** [comment]
In debug.log
[2020-03-17 10:22:49] main.CRITICAL: Payment Error: currency is currently not supported [] []

I think it come from my fault when i change this code in omise-offsite-internetbanking-method.js line 94
`return this.getOrderCurrency().toLowerCase() === 'thb' && this.getStoreCurrency().toLowerCase() === 'thb';`
to
`return this.getOrderCurrency().toLowerCase() === 'thb';`

But when try with original source it always  show 'Option available only for orders in THB' while 
currency is THB & currency symbol is ฿. Maybe it come from my config in admin not correct :(. Can you have me to check this? Thanks!

![omise-issue-3](https://user-images.githubusercontent.com/37996592/76848785-d9ef7500-6876-11ea-8ece-8f7318d7ad91.png)

**Comment by congbk2910** [comment]
> also, did you install plugin via `composer` or manually?

I install via composer

**Comment by congbk2910** [comment]
I have resolved my issue. It come from my fault. Sorry to disturb,I will close this issue. Thank you so much.
