### ISSUE TITLE
Internet Banking SCB Order Success When payment cancel - ONLY happens in Live mode

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#251]
Your Internet Banking Solution here in Thailand causes so many problems. I have disabled it for well over a year now and version 2.10 still the same problems

1. Customer Cancels on banking page. In live mode with SCB its still creates the order success page with no error. Like the payment has been made. In sandbox mode it creates and error message.
2. Is there not a way customers can be returned to the payment page when they click cancel?? 

Magento version 2
omise-magento version 2.10

**Comment by aashishgurung** [comment]
We are closing this issue since it's already been resolved by [this PR](https://github.com/omise/omise-magento/pull/334). Plus, we have [dropped SCB from internet banking](https://www.omise.co/internet-banking). Thank you.
