### ISSUE TITLE
Paying By Debit/Credit Card - invalid security code: the security code is invalid

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#252]
This is a bit of a strange one. I cannot reproduce the issue but we get soooo many complaints. 

Magento 2.3.2
omise -magento 2.10
Magento Omise Settings
Credit Card Solution Enable
Payment Action Authorize and Capture
3-D Secure Yes

Customer is on the checkout page enters card details and receive a payment error message. In Omise backend it reports invalid security code: the security code is invalid

We have spoke to sooo many customers and they all say the same thing. The security code is 100% correct and they have used their cards on other sites without problems

What could be causing this?
The only thing i could think of is browser auto complete forms and the security code field gets auto field with a password???

Do you have any ideas?

**Comment by BrainTurner** [comment]
Hello,

When we update to version 2.16 this problem when away But now with version 2.18.1 its back again.

I notice in omise website you list the error as "invalid security code: the security code is invalid" but in magento system logs its a different error "[2021-07-05 03:20:11] main.CRITICAL: Payment Error: expiration date cannot be in the past [] []
[2021-07-05 03:20:11] main.CRITICAL: Placing an order with quote_id 19456 is failed: การทำธุรกรรมถูกปฏิเสธ กรุณาลองใหม่อีกครั้งในภายหลัง [] []"

Is this problem caused by PR 291??
We are using magento 2.3.7 with PHP 7.3

Its a really big problem with our customers

**Comment by som-m** [comment]
Hi @BrainTurner, could you please contact support@omise.co with the following information for further investigation?

- Omise account email
- Charge ID
- Date/Time
- Error message
