### ISSUE TITLE
Need Omise's keys dialogue in checkout

### ISSUE THREAD

**Issue by mr6502** [omise/omise-magento#26]
We are running Magento 1.9.2.4 using a custom checkout (Firecheckout module).  We've installed omise-magento 1.9.0.6 which says this issue is fixed.  As a dependency we have omise-php 2.5.0 (Side note:  The omise-magento readme doc says it requires 2.4.0 but we couldn't get it to work with 2.4.0 either).

![spectacle bh4872](https://cloud.githubusercontent.com/assets/21123937/18174528/c133eb7a-7065-11e6-974d-aad83a8c0e97.png)

Please can you suggest how to investigate or fix for this?

**Comment by guzzilar** [comment]
@mr6502 Hi,

Currently, we are investigating this issue.
From what we know right now, it could be possible that our extension doesn't support with Firecheckout module.

However, we will keep inform you when we find a better solution to solve this issue.

And, thanks for report us :D
Nam

**Comment by guzzilar** [comment]
Hi,

We just updated [README.md](https://github.com/omise/omise-magento/blob/master/README.md) to explain about using Omise Magento with One Page Checkout extension.

You could read at the topic "Using omise-magento with One Page Checkout (OPC) extension" from the link below,
https://github.com/omise/omise-magento/blob/master/README.md#using-omise-magento-with-one-page-checkout-opc-extension

Nam

**Comment by guzzilar** [comment]
@mr6502 Hi, just wanted to give you an update, the solution has been provided at release [v1.12](https://github.com/omise/omise-magento/releases/tag/v1.12).

Thanks for reported the issue :)
Nam.
