### ISSUE TITLE
Payment declined when use saved credit card

### ISSUE THREAD

**Issue by junnhouse** [omise/omise-magento#262]
<img width="954" alt="Screen Shot 2020-06-11 at 12 11 19" src="https://user-images.githubusercontent.com/40013784/84354425-0ce1a480-abeb-11ea-97c0-afa5e237082d.png">

error like this

**Comment by mayurkathale** [comment]
Hi @junnhouse , I was unable to reproduce this issue with latest plugin update. Can you please provide me more information? such as, versions of Magento Framework, Php, Plugin.

**Comment by mayurkathale** [comment]
@junnhouse from error message it looks like session has expired while you were trying to place the order.

**Comment by mayurkathale** [comment]
Closing this ticket as being inactive.
