### ISSUE TITLE
Magento 2.4.2 compatibility?

### ISSUE THREAD

**Issue by PorraphitChuasuk** [omise/omise-magento#286]
Any idea why composer requirement is stick on `"magento/magento-composer-installer": "0.1.13"` ?

This is cause this extension cannot be installed on Magento 2.4.2 which using version `0.2.0`

https://github.com/omise/omise-magento/blame/934ae23de1c046aecab55cf68a4685c48b11157d/composer.json#L18

**Comment by danfowler** [comment]
Hi @PorraphitChuasuk thanks for raising. We should be addressing this soon.

**Comment by Ashraf-alkibsi** [comment]
Hi @PorraphitChuasuk ,
sorry for the late reply. we just updated the plugin(v2.18) to support Magento 2.4.2.
It can be installed with `composer require omise/omise-magento`. [official docs](https://www.omise.co/magento-plugin)
The first time to run the command can take few minutes for composer to check for compatible packages. 

Please let us know if you still having issues installing the plugin
