### ISSUE TITLE
Magento 2.4.3-p1: After amount captured 2 invoices are generated!

### ISSUE THREAD

**Issue by donniesg** [omise/omise-magento#324]
I have been using Omise with my Magento 2.2.10 setup. It has been quite smooth so far.

I am try in the process of migrating to Magento 2.4.3-p1. I have setup a development environment on 2.4.3-p1. Php version 7.4. All codes are updated to the latest including Omise to 2.20.3. Omise is running in SANDBOX mode.

As I am from Singapore, I accept credit cards and PayNow on my site. 

**For credit cards**, I have configured payment action to "Authorized and capture" amount. 
I entered an other using credit card payment and entered valid credit card details:-
**Expected**: Upon order confirmation, the amount is suppose to be captured, order status changed to "Processing" and one invoice generated "Paid".
**Actual**: Upon order confirmation, the amount is suppose to be captured, order status changed to "Processing" and 2 invoices are generated. One with order amount and status "Pending", invoice number is <order number>. The 2nd order has zero amount and status "Paid", invoice number=<order number>-1.

**For PayNow**, 
I entered order and select PayNow as payment option. Amount is set to captured on Sandbox backend. Run sync order status on Magento backend:-
**Expected**: Order confirmation status change from Pending Payment to Processing. Invoice status change from pending to Paid.
**Actual**: Order confirmation status change from Pending Payment to Processing. Invoice remains as pending status. A new invoice with zero amount is created with paid status and invoice number =<order number>-1.

I have also tried using Paypal as payment and the order process does not have similar problems.

**Comment by aashishgurung** [comment]
We are closing this issue since it's already been resolved by this PR [#387](https://github.com/omise/omise-magento/pull/387). If this issue still persists, please feel free to reopen it and we’ll take another look. Thank you.
