### ISSUE TITLE
3DS Activate - 3DS Auth fails but Invoice is gernerated and email sent

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#372]
Hello

I have a problem that in my env we have auto invoice email setup. So when an invoice is generated an email is sent to the customer with the order/invoice details.

A couple of weeks ago omise activated 3DS on credit and debit cards. We have noticed that the invoice is generated  before the auth of 3ds is completed thus means the order/invoice is created and a email is sent to the customer.

If the auth fails the invoice/order is cancelled however the customer already has am invoice.

Maybe i am wrong but i think the creation of the order/invoice should happen after 3ds is approved and completed. We had a customer last week who got 5 emails and on her account got 5 cancelled orders.

Preconditions (*)
1. Magento 2.3.7-p3
2. Omise 2.27.0

Steps to reproduce (*)
1. Complete checkout
2. Enter incorrect credit card details

Expected result (*)
Email and creation of order/invoice should happen after 3DS finishes and is approved

Actual result (*)
an order/invoice is created before 3ds and is cancelled if failed. When customer retries another order is created.

**Comment by aashishgurung** [comment]
@BrainTurner You can go to our plugin settings page, go to credit card section and change the `Generate invoice at order status` field value to `processing`. This will generate invoice after the payment is complete.

<img width="724" alt="Screenshot 2566-04-20 at 15 16 14" src="https://user-images.githubusercontent.com/101558497/233303895-eb38882e-7a49-4d09-8546-3a26797453f3.png">

If you have more questions or concerns, please feel free to reach out and we’ll do our best to assist you.
