### ISSUE TITLE
Webhooks not working - Invalid payment method. Please contact our support if you have any questions.

### ISSUE THREAD

**Issue by BrainTurner** [omise/omise-magento#465]
### Expected behavior

Customer create an order, select the payment method "Prompt Pay" or "Credit / Debit", enter details or scan code. Order is place into magento, sales order email is sent to the customer and webhook updated if payment is complete or not.

### Actual behavior

Customer create an order, select the payment method "Prompt Pay" or "Credit / Debit", enter details or scan code. Order is place and set to "payment pending". No sales order email is send and Its doesnt update unless you click the "Sync Order Status Maunaly". When you click  "Sync Order Status Maunaly" then the sales order email is sent to customers and status changes to "Proccessing"

### Steps to reproduce the issue

Customer create an order, select the payment method "Prompt Pay" or "Credit / Debit", enter details or scan code.

### Logs

No logs or errors in debug logs. However when i copy the webhock URL from the OPN panel its returns a error message of "Invalid payment method. Please contact our support if you have any questions"

### Name and version information

Magento 2.4.6-p3
Omise Version 3.5.2 (also tried order versions)
php 8.1
nginx

**Comment by aashishgurung** [comment]
@BrainTurner Apologies for the delayed response. Could you clarify whether you were using standard webhook or a dynamic webhook? Also, can you please provide us the section of plugin settings that configures webhook? Similar to the example below. Please don't forget to mask your URL.

<img width="707" alt="Screenshot 2567-01-22 at 18 34 02" src="https://github.com/omise/omise-magento/assets/101558497/1e287fa6-7641-4d71-8e89-8d3fba318e49">

**Comment by BrainTurner** [comment]
@aashishgurung Thank you for the responce.
![image](https://github.com/omise/omise-magento/assets/41930785/5a57a61c-8e96-4543-8b85-ce910583c46c)

Image attached above with the current config using module version 2.32.0 and omise-php 2.16.0. The reason why we downgraded to this version was just for testing purposes and we have another site using this version with magetno 2.4.6-p3 without any issues. However we can confirm the issue still happens with the latest version.

I am not sure what is happening. We just upgraded to magento 2.4.6-p3 with php 8.1 and the issues started. The only other changed was we migrated to a godaddy VPS. Could it be an IP block problem?

We have tried everything in a test version and no matter what we try always the same error.
 
A Point in the right director to fix this issue would be appreciated.

**Comment by aashishgurung** [comment]
@BrainTurner We added the dynamic webhook feature from version v3.4.0. Does this issue persist only in v3.5.2? The webhook URL isn’t supposed to respond with the message “Invalid payment method. Please contact our support if you have any questions.“.

Is it possible for you to try the problematic version on your test site and email us a screenshot of the plugin’s setting at [support@opn.ooo](mailto:support@opn.ooo)? We can continue our discussion there, as we may need more information to resolve this issue.

**Comment by aashishgurung** [comment]
@BrainTurner We’re going to close this case as you and our support team have successfully resolved the issue. In case of any recurrence, please don't hesitate to reopen it with additional details, and we will be more than happy to take another look.

**Comment by BrainTurner** [comment]
@aashishgurung Thank you very much for you help. Contacting the support team was very helpful. It turned out the error was happening due to an invalid chain in the ssl. WE didnty notice this due to no errors in google chrome or other browsers about ssl issues.

Once we fixed the ssl chain everything worked normal again.
