### ISSUE TITLE
setup:di:compile Error

### ISSUE THREAD

**Issue by sarunyu** [omise/omise-magento#54]
[takra@th94 public_html]$ php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 28.0 MiB

  [Exception]
  Notice: Constant OMISE_PUBLIC_KEY already defined in /home/takra/domains/takraexpress.com/public_html/app/code/Omise/Payment/vendor/omise/omise-php/tests/omise/TestConfig.php on line 4

setup:di:compile

**Comment by nimid** [comment]
Hello @sarunyu ,

Thank you very much that you informed the issue that you found.

For workaround, please delete a directory, `tests/`, that stored inside the directory `omise-php/`.

For example from the above comment:

1. `rm -rf /home/takra/domains/takraexpress.com/public_html/app/code/Omise/Payment/vendor/omise/omise-php/tests/`

And run the commands below:

2. `composer require omise/omise-php:2.6.0` (This command must be run at the root directory of Magento 2, `/home/takra/domains/takraexpress.com/public_html/`)

3. `php bin/magento setup:di:compile`

4. `php bin/magento setup:upgrade`

Thank you very much.

**Comment by sarunyu** [comment]
thank you bro.
