### ISSUE TITLE
[ReflectiontionException]

### ISSUE THREAD

**Issue by prasertkv** [omise/omise-magento#84]
-Magento v2.1.6
When use command  "setup:di:compile"  Will result below
![image](https://cloud.githubusercontent.com/assets/27570520/25065315/0c1f2292-2238-11e7-978a-fdceb7ec3a04.png)

**Comment by guzzilar** [comment]
Hi @prasertkv 

Can you try remove file at `app/code/Omise/Payment/Model/Ui/OmiseConfigProvider.php` then, run the command again?

Please let me know if this problem still occurs.
Nam.

**Comment by guzzilar** [comment]
Hi, this issue has been solved at Omise-Magento v2.3.
ref: https://github.com/omise/omise-magento/releases/tag/v2.3
