### ISSUE TITLE
Extension Patch ล่าสุดสำหรับ Magento 1.x มีปัญหา

### ISSUE THREAD

**Issue by A-Kits** [omise/omise-magento#99]
Extension Patch ล่าสุดมีปัญหานะครับ 
เวลาลูกค้าทำรายการเรียบร้อยแล้ว แกติมันต้องขึ้น “เตรียมจัดส่ง” แต่พออัพเดทแล้วมันขึ้น “รอชำระเงิน” 
ทั้งๆที่ order มีการ capture เรียบร้อย มียอดเงินเข้ามาในบัญชี omise แล้วครับ   แล้วไม่สามารถแก้ Status ของ order เป็นอย่างอื่นได้ด้วยครับ
Patch ก่อนหน้านี้ไม่เป็นนะครับ Patch แรกสุดคือเวลาชำระเงินเรียบร้อย จะขึ้น “รอส่งสินค้า” ตามที่ตั้งไว้ 
ผมลงทะเบียนเปิดใช้ 3-D กับ omise เรียบร้อยและใช้งานได้ปกติ จนมา Patch นี้ที่มีปัญหาครับ
รบกวนช่วยแก้ด่วยด้วยครับ หรือส่งลิงค์ Patch เก่ามาให้ใช้ Load กลับไปใช้ก่อนก็ดีครับ

**Comment by guzzilar** [comment]
patch ล่าสุดที่คุณ @A-Kits คือตัว https://github.com/omise/omise-magento/pull/97 หรือปล่าวนะครับ (เป็นตัวที่ผมอัพเดทเมื่อช่วงหัวค่ำเมื่อคืน)

**Comment by A-Kits** [comment]
พึ่งโหลด ตอน11:00วันนี้ครับ อัพเทดล่าสุดน่าจะหัวค่ำเมื่อวานนี้แหลาพครับ

**Comment by A-Kits** [comment]
ตัว 1-stable ครับ  https://github.com/omise/omise-magento/tree/1-stable

**Comment by guzzilar** [comment]
@A-Kits ผมรบกวนขอภาพ screenshot ของหน้า order detail ในส่วนของ order status (ประมาณด้านล่างสุดของจอ) ได้ไหมครับ

หน้าจอประมาณภาพด้านล่างครับ (สามารถลบ order id และ charge id ออกจากภาพได้นะครับ)
![006](https://user-images.githubusercontent.com/2154669/32696731-75d29b68-c7b2-11e7-86f8-e7bf3cb7c3da.png)

**Comment by A-Kits** [comment]
ตามรูปเลยครับ 
ในส่วยของช่อง สถานะ ปกติมันจะมีให้ปรับจาก “รอชำระเงิน” เป็นสถานะอื่นได้ แต่พออัพเดทแล้ว ปรับ สถานะเป็นอย่างอื่นไม่ได้เลยครับ

**Comment by guzzilar** [comment]
@A-Kits เหมือนรูปจะไม่ขึ้นครับ รบกวนลองอัพโหลดใหม่อีกรอบได้ไหมครับ

**Comment by A-Kits** [comment]
<img width="482" alt="screen shot 2560-11-13 at 14 45 10" src="https://user-images.githubusercontent.com/23354740/32714847-4454fa2e-c882-11e7-929f-5cac8951ead7.png">

**Comment by guzzilar** [comment]
@A-Kits ขอบคุณมากครับ ผมคิดว่าน่าจะเกิดจากปัญหา PHP version ไม่ซัพพอร์ทโค้ดในบางจุด
ผมลองเช็คจากใน log PHP ที่คุณ @A-Kits ใช้อยู่เป็น 5.4 แต่ตัวที่ผมเทสเป็น 5.6

ยังไงผมขอเทสเพิ่มเติมในส่วนของ PHP 5.4 ถ้าพบปัญหาในส่วนไหนจะรีบแจ้งกลับไปนะครับ

**Comment by guzzilar** [comment]
@A-Kits ผมรบกวนลอง flush Magento cache ดูหน่อยได้ไหมครับ
![screen shot 2560-11-14 at 11 07 25 am](https://user-images.githubusercontent.com/2154669/32762476-17aa254e-c92c-11e7-863a-611ebf908f89.png)

หน้าจอจะประมาณนี้
พอดีผมลองใน PHP/5.4.45 Magento/1.9.3.4 แล้วแต่ไม่เจอ issue ตัวนี้เลยครับ

**Comment by A-Kits** [comment]
Cache หลังอัพเดท patch ทุกครั้งแล้วครับ

**Comment by guzzilar** [comment]
@A-Kits ถ้ายังไม่หาย ผมรบกวนคุณ @A-Kits พอจะโชว์ php error log กลับมาหน่อยได้ไหมครับ

**Comment by A-Kits** [comment]
มีปัญหาเพิ่มครับ เวลากดชำระเงินด้วยบัตรเครดิต ใช้  OTP 
จ่ายสำเร็จมีเงินเข้าบัญชี omise แต่หน้าจอเว็บขึ้น HTTP ERROR 500 
แล้วไม่ redirect กลับ หน้าเว็บเดิมครับ 
<img width="767" alt="screen shot 2560-11-14 at 13 46 01" src="https://user-images.githubusercontent.com/23354740/32766648-7a67048e-c942-11e7-8a4f-4519901bed33.png">

**Comment by guzzilar** [comment]
@A-Kits เป็นปัญหาเดียวกับที่ตัว order ไม่อัพเดทเลยครับ ผมรบกวนคุณ @A-Kits ส่ง error log จากฝั่ง server เพื่อตรวจสอบเพิ่มเติมได้ไหมครับ

ถ้าตัว server ที่ใช้เป็น Apache สามารถตรวจสอบได้ที่ https://askubuntu.com/questions/14763/where-are-the-apache-and-php-log-files
ถ้าเป็น Nginx สามารถตรวจสอบได้ที่ https://stackoverflow.com/questions/1706111/where-can-i-find-the-error-logs-of-nginx-using-fastcgi-and-django

**Comment by A-Kits** [comment]
ส่งไปทาง email ครับ

**Comment by guzzilar** [comment]
หมายเหตุ: issue นี้ได้รับการแก้ไขเรียบร้อยแล้ว
สำหรับรายละเอียด patch สามารถตรวจสอบได้ที่ PR https://github.com/omise/omise-magento/pull/100 ครับ

@A-Kits. ขอบคุณที่แจ้งปัญหาเข้ามาและช่วยผมทดสอบ/หาสาเหตุของปัญหานะครับ 
หากติดปัญหาการใช้งานใดๆ เพิ่มเติมสามารถแจ้งเข้ามาได้ตลอดเลยครับ 😃 👍
